language: java
jdk:
  - openjdk11
notifications:
  slack:
    secure: J+TBEIukXda5GoghSg740zLv3y1xTTG4ruRlLQuMECu4v8siUtforG3FqlHNP+vVD+ga9jL0GHaPK7ubsxYnuCh2NZA1DfHJ/aw+zqg0H8Tzzgu6H6R/HWecvmUdPBlN8uRK1Grka38iOBX7itpd/sQSiN3lqV7tY7JbzSCFPHP7BYrxfYMPnl9ZU7vXvTWxhLu6c0Nv/MivEOEOGk0VQMG12PjO912M39a1RPGmje2ApsKB6ZCb6nyS5z/WkQxsH2DrHEaUKwCVdOaRubjTR58y1IMavVrgJxwm6G3yftiVA8KMDfFHPBKKW/45rcfCTK8fk27mPdqN/zPF3QATgZhcPdYLa4VRxCS2KuZoTQ8OX5/vHYPQMcE4ncSlpsEkmuv26wPOc5IiGx+Td1swMNRlg9M0CC54EVUZDw5JRRqZ3C6py/gPPFy3B/P2BcfZeWDwIxj9g/MYrPdykSmAlKV5JzO03WfNw6uH1QapNvQXUaNOrHqVWV9yaITxGsSEZrlODTdCI+UhT03rB0WrlZe1GRDR96JUElgbRItOl7sfCdbc0PUUF0qSbjKmTSo3A5Gy9cu6trKDf/tgA6aGRfrPSPJQkVXdBFMRxL4DLgE2NsKuVK8j/taMl1fqalykDz/bnEgvHzjGuB7PdtcgkR440Zty59PhsvPluAiFSpo=
