language: java
jdk:
  - openjdk11
notifications:
  slack:
    secure: is4Gz4uJR7M9jZpcwiWzg13u7EWVZRroAHrRXWCXZlbnVOZNkJoiEyW1qfDQEKG7y9EuaEJ0TJn1ZhfsWV7sigmS/PpNVK4d2DC0ydLln1ZrAmFCzGB1BWXJbi92alH6rv39cKeJJgdh2HlLY8erU8FO+zNrhRbCtcugmVffXpZbJSpsxEzcgfqfMk/xDTDKK8eRDy+J+U3t5g/H6PYvRucPwheHFi3rrnDzV/r0moX8zxcjPKFDoJY0NmjECv2TxqNulieAoY0PVVPBDJpdH5+H5BCZYPutu8Y7ZrueJihYbhFuBQIn0a6glJbrE+9C5QLNdkUIp/kf/J8SKK3ydrrUkChk4cfj/cxbpRFb2Qk5SBFtpcLsGaaZa39vC6azhpqsM7nKwS/YERyM8NGNQ7qpDX2LZF7P+/UfFX8D60eY0u53JamwVTiH3yf5qEJPaDmO0IzK9r9jn8JFtaq+sLardAkyW1GxT7bjPJr5rLbNj6GPcyFL/8pk+lANLiCIuGvZa+ZL+h/meKrkfG18Iuzgl5viKF9qVI2onHWM3Gy1MnqOPFHs51atAHH6azAriDm6nSKJmr49pqa9m4Qpdi7LetAyr0PwxRsAABcoAWFN8Gbmr0Gmc+5hYB0zWRbExFPyblslIMubcyd2Z6wxjgKNswwT1gLtS2RnDQuItWI=
